### ISSUE TITLE
import me.tade.*

### ISSUE THREAD

**Issue by segalws** [Shevchik/TNTRun#11]
where to get?
import me.tade.trgrenade.Main;
import me.tade.trgrenade.ParticleEffect;

**Comment by Shevchik** [comment]
Nowhere, this is from grenade addon, and sohuld be removed from tntrun source code.
I'm not working on tntrun anymore so you should ask tade.

**Comment by tade159SK** [comment]
Hi, you can remove that, this only using addon grenade, not tntrun plugin
